import Head from "next/head";
import { useEffect, useState } from "react";
import "@mantine/core/styles.css";
import Body from "@/common/Body";

export default function Home() {
  const [clientContent, setClientContent] = useState(null);
  useEffect(() => {
    setClientContent(<Body />);
  }, []);
  return (
    <>
      <Head>
        <title> LUNGOMARE DÖNER & PIZZERIA </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="shortcut icon"
          href="assets/images/favicon.png"
          type="image/x-icon"></link>
      </Head>
      <div>{clientContent ? clientContent : <p>Loading...</p>}</div>
    </>
  );
}
